# Generated by Django 2.1.5 on 2019-02-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_massage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Massage',
            new_name='Message',
        ),
    ]
