# Generated by Django 2.1.5 on 2019-02-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190210_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='e_mail',
            new_name='email',
        ),
    ]
