# Generated by Django 2.1.5 on 2019-02-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_auto_20190207_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(to='shelf.Book'),
        ),
    ]
